feat: rsync with lock file

diff --git a/ansible/files/rsync-upload.sh.j2 b/ansible/files/rsync-upload.sh.j2
--- a/ansible/files/rsync-upload.sh.j2
+++ b/ansible/files/rsync-upload.sh.j2
@@ -1,2 +1,37 @@
-#! /bin/bash
+#!/bin/bash
+
+# Lock functionality taken from https://stackoverflow.com/questions/1715137/what-is-the-best-way-to-ensure-only-one-instance-of-a-bash-script-is-running
+
+## Copyright (C) 2009 Przemyslaw Pawelczyk <przemoc@gmail.com>
+##
+## This script is licensed under the terms of the MIT license.
+## https://opensource.org/licenses/MIT
+#
+# Lockable script boilerplate
+
+LOCKFILE="/var/lock/rsync.service"
+LOCKFD=99
+
+# PRIVATE
+_lock()             { flock -$1 $LOCKFD; }
+_no_more_locking()  { _lock u; _lock xn && rm -f $LOCKFILE; }
+_prepare_locking()  { eval "exec $LOCKFD>\"$LOCKFILE\""; trap _no_more_locking EXIT; }
+
+# ON START
+_prepare_locking
+
+# PUBLIC
+exlock_now()        { _lock xn; }  # obtain an exclusive lock immediately or fail
+exlock()            { _lock x; }   # obtain an exclusive lock
+shlock()            { _lock s; }   # obtain a shared lock
+unlock()            { _lock u; }   # drop a lock
+
+### BEGIN OF SCRIPT ###
+
+
+
+
+# Simplest example is avoiding running multiple instances of script.
+exlock_now || exit 1
 rsync --bwlimit="{{client.rsync.max_bandwith}}" --remove-source-files --progress -r "{{client.data_folder}}" "rsync://{{ hostvars[groups['server'][0]]['inventory_hostname'] }}:{{server.rsync.port}}/files"
+unlock
